# Generated by Django 5.1.4 on 2025-01-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('steps_of_cooking', models.TextField()),
                ('time_for_cooking', models.IntegerField(default=15)),
            ],
        ),
    ]
