# Generated by Django 5.1.4 on 2025-01-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0003_recipe_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user',
            new_name='author',
        ),
    ]
