# Generated by Django 5.1.4 on 2025-01-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0004_rename_user_recipe_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-title', 'created_at'], 'verbose_name': 'Recipe'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
