# Generated by Django 5.1.4 on 2025-01-20 11:25

import recipesapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesapp', '0006_recipe_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=recipesapp.models.recipe_photo_directory_path),
        ),
    ]
